# Generated by Django 4.1 on 2022-08-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
