# Generated by Django 4.1 on 2022-08-31 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='instituicao',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
