# Generated by Django 4.1 on 2022-08-31 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_instituicao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
