# Generated by Django 4.1 on 2022-08-30 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Faces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgId', models.CharField(max_length=255)),
                ('faceId', models.CharField(max_length=255)),
                ('bboxWidth', models.FloatField()),
                ('bboxHeight', models.FloatField()),
                ('bboxLeft', models.FloatField()),
                ('bboxTop', models.FloatField()),
                ('eyeLeftX', models.FloatField()),
                ('eyeRightX', models.FloatField()),
                ('eyeLeftY', models.FloatField()),
                ('mouthLeftX', models.FloatField()),
                ('mouthLeftY', models.FloatField()),
                ('mouthRightX', models.FloatField()),
                ('mouthRightY', models.FloatField()),
                ('noseX', models.FloatField()),
                ('noseY', models.FloatField()),
                ('roll', models.FloatField()),
                ('yaw', models.FloatField()),
                ('pitch', models.FloatField()),
                ('brightness', models.FloatField()),
                ('sharpness', models.FloatField()),
                ('confidence', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('collection_id', models.IntegerField()),
                ('isIndexed', models.BooleanField(default=False)),
                ('imgHash', models.CharField(max_length=255)),
                ('imgId', models.CharField(max_length=255)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.event')),
            ],
        ),
    ]
