# Generated by Django 4.1 on 2022-08-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_faces_face_rename_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
